[Fix] OD-50 Showing current date/time if option is selected even if data source is connected.
Fliplet/fliplet-widget-form-builder pull request #331
Opened 2020-09-29 17:46 UTC by YaroslavOvdii

@sofiiakvasnevska 

## Issue
https://weboo.atlassian.net/browse/OD-51

## Description
Check if `Always autofill with current date` selected and show the current date then.

## Screenshots/screencasts
https://share.getcloudapp.com/OAuJw5Kq

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko

2020-09-30 13:25 UTC, tonytlwu requested changes

2020-09-30 13:25 UTC, tonytlwu commented on js/libs/form.js
> +              if (regexDateFormat.exec(fieldData) && !showCurrentDateTime || regexISOFormat.exec(fieldData) && !showCurrentDateTime) {
```suggestion
              if (regexDateFormat.exec(fieldData) && !showCurrentDateTime || regexISOFormat.exec(fieldData) && !showCurrentDateTime) {
```
```suggestion
              if ((regexDateFormat.exec(fieldData) || regexISOFormat.exec(fieldData)) && !showCurrentDateTime) {
```

2020-10-06 07:12 UTC, YaroslavOvdii commented on js/libs/form.js
> +              if (regexDateFormat.exec(fieldData) && !showCurrentDateTime || regexISOFormat.exec(fieldData) && !showCurrentDateTime) {
@tonytlwu Fixed

2020-10-06 10:46 UTC, tonytlwu approved these changes
@sofiiakvasnevska This is ready for testing

Risk: Medium
Affected: Date and time fields
Verify: Date and time fields are correctly loading data from data sources

2020-10-06 10:48 UTC, merged