OD-423 [Fix]  Added support for IE11 and Safari to render timePicker
Fliplet/fliplet-widget-form-builder pull request #380
Opened 2021-04-15 13:11 UTC by AndrRyaz

@sofiiakvasnevska 

## Issue

OD-423 https://weboo.atlassian.net/browse/OD-423

## Description
Added support of this feature for IE11 and Safari
## Screenshots/screencasts
http://somup.com/crf12tbK01
## Backward compatibility
This change is fully backward compatible.
## Reviewers
@upplabs-alex-levchenko @ivandevupp @YaroslavOvdii

2021-04-22 09:04 UTC, squallstar requested changes
Rejected +1

2021-04-22 09:04 UTC, squallstar commented on js/components/time.js
> +      LOCAL_FORMAT: moment.localeData().longDateFormat('LT'),
I already reviewed this in a different PR. Please open this PR without these changes once the other is merged.

2021-04-22 09:52 UTC, AndrRyaz commented
@squallstar, I already fixed this, needed to update on master branch

2021-04-27 08:56 UTC, squallstar approved these changes
@sofiiakvasnevska this is ready to be deployed on **staging** for QA.

- **Risk**: High
- **Affected**: Forms with date fields
- **Verify**: Verify forms with date fields work as expected

2021-04-27 09:02 UTC, merged