OD-361 [Feature] Users will see new layout of the file field.
Fliplet/fliplet-widget-form-builder pull request #383
Opened 2021-05-11 10:13 UTC by YaroslavOvdii

@sofiiakvasnevska 

## Issue
https://weboo.atlassian.net/browse/OD-361

## Description
Changed file field layout.

## Screenshots/screencasts
https://share.getcloudapp.com/Jru49ANG

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko @AndrRyaz

2021-05-11 13:19 UTC, tonytlwu requested changes
Rejected +1

2021-05-11 13:19 UTC, tonytlwu commented on css/form.css
> +  color:red;
```suggestion
  color: #e03629;
```

2021-05-12 07:12 UTC, YaroslavOvdii commented on js/components/file.js
> +    isValueUrlLink: function() {
@tonytlwu You right we could use `Flipet.Media.isRemoteUrl()` I'll change it.

2021-05-12 07:18 UTC, YaroslavOvdii commented on templates/components/file.build.hbs
> +        <span class="file-info-uploaded">Uploaded: <b>\{{ showLocalDateFormat(file.createdAt) }}</b></span>
@tonytlwu Fixed

2021-05-12 07:18 UTC, YaroslavOvdii commented on js/components/file.js
> +        var newFiles = _.map(files, function(file) {
@tonytlwu Fixed

2021-05-12 07:18 UTC, YaroslavOvdii commented on js/components/file.js
> +    isValueUrlLink: function() {
@tonytlwu Fixed

2021-05-12 07:18 UTC, YaroslavOvdii commented on css/form.css
> +  color:red;
@tonytlwu Fixed

2021-05-12 08:29 UTC, tonytlwu requested changes
Rejected +1

2021-05-12 08:29 UTC, tonytlwu commented on css/form.css
> +  color:#e03629;
```suggestion
  color: #e03629;
```

2021-05-12 09:00 UTC, YaroslavOvdii commented on css/form.css
> +  color:#e03629;
@tonytlwu Fixed

2021-05-12 09:08 UTC, tonytlwu approved these changes
@sofiiakvasnevska This is ready for testing

Risk: High
Affected: All form components using the Files field
Verify: Users can load and upload files in forms

Squash and merge: Use PR title

2021-05-12 12:48 UTC, merged