OD-490 [Feature] Data and Time fields preferences improvements
Fliplet/fliplet-widget-form-builder pull request #386
Opened 2021-05-13 15:18 UTC by AndrRyaz

@sofiiakvasnevska 

## Issue
OD-490 https://weboo.atlassian.net/browse/OD-490
## Description
Added new fields to radio and remove unnecessary fields
## Screenshots/screencasts
http://somup.com/crhIoDFMMs
## Backward compatibility
This change is fully backward compatible.
## Reviewers

2021-05-17 16:40 UTC, tonytlwu requested changes
Rejected + 1

The requirement specifies:

> When the user chooses **one of the default value types to autofill with current date/time**, the When applying the current date/time field should appear.

The default value types that autofill with the current date/time are:

* Autofill with current date if it's empty
* Always autofill with current date

In 0:49 of http://somup.com/crhIoDFMMs you clicked on **Autofill with current date if it's empty**, but the **When applying the current date** field did not appear. This needs to be corrected.

2021-05-17 16:40 UTC, tonytlwu commented on js/components/date.js
> +
No empty lines at the end of `{}`

2021-05-17 16:40 UTC, tonytlwu commented on js/components/date.js
> +    if(this.autofill === 'empty') {
```suggestion
    if (this.autofill === 'empty') {
```

2021-05-24 07:25 UTC, AndrRyaz commented on js/components/date.js
> +    if(this.autofill === 'empty') {
fixed

2021-05-24 07:25 UTC, AndrRyaz commented on js/components/date.js
> +
fixed

2021-05-24 07:25 UTC, AndrRyaz commented
@tonytlwu new video - http://somup.com/crhZiTqjO3

2021-05-24 15:53 UTC, tonytlwu requested changes
@AndrRyaz In 0:10 of https://screencast-o-matic.com/watch/crhZiTVfS7n it shows that you clicked on **Autofill with a specific date if it's empty**. According to https://weboo.atlassian.net/browse/ID-904 Fig. 2 and specification 1b. users should be able shown a date picker and then be able to select a date. But in the video, no additional field was shown.

Rejected +1

2023-05-04 11:30 UTC, closed without merging