XOR-252 [FEAT] Add "Select all" functionality for checkboxes
Fliplet/fliplet-widget-form-builder pull request #451
Opened 2022-07-07 09:22 UTC by anshukdutt

### Product areas affected
Fliplet-Form builder

### What does this PR do?
Ensures to add selectAll functionality for checkboxes in via form builder configuration & JS API
### JIRA ticket
[JIRA](https://weboo.atlassian.net/browse/XOR-252)

### Result
Add any relevant sample input/output, screenshots or screen recordings.

[Screen Recording](https://api.media.atlassian.com/file/6fbff0a6-b23e-42fe-a767-9f9190e79077/artifact/video_1280.mp4/binary?client=435f5956-a841-4ea9-80ca-d94a2672bba6&collection=&max-age=2592000&token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI0MzVmNTk1Ni1hODQxLTRlYTktODBjYS1kOTRhMjY3MmJiYTYiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOmI1OTJmNGM1LTZmZDYtNGU3Zi1hZTYwLTJlZDg1NjI3MWZiOSI6WyJyZWFkIl0sInVybjpmaWxlc3RvcmU6ZmlsZTplNjRhNzJlZi1jY2VlLTQzM2UtYWM3Yi0wNmQzNDA5ZWNhOGMiOlsicmVhZCJdLCJ1cm46ZmlsZXN0b3JlOmZpbGU6OTZhZDFmNzgtMWViMi00YzBkLWEzZmYtYTc0MjRmNmYwNzY5IjpbInJlYWQiXSwidXJuOmZpbGVzdG9yZTpmaWxlOjZmYmZmMGE2LWIyM2UtNDJmZS1hNzY3LTlmOTE5MGU3OTA3NyI6WyJyZWFkIl0sInVybjpmaWxlc3RvcmU6ZmlsZTo1OWM3MGJmZS02YTIyLTQ4ODAtYmNmYS1lMGU5NDYyMTEwMWUiOlsicmVhZCJdLCJ1cm46ZmlsZXN0b3JlOmZpbGU6MzMxZWM1ODItNzdlYS00NzFmLWJlZmMtYWIyMzAxYmIyMTQwIjpbInJlYWQiXSwidXJuOmZpbGVzdG9yZTpmaWxlOjBiYjYzODhjLTRiNjMtNDhlYi1hY2E3LWQ3YTIwY2RlZGQzMyI6WyJyZWFkIl0sInVybjpmaWxlc3RvcmU6ZmlsZTpjNDdjMmU5Yy1kYjAyLTRlNDUtYmFmOC0wYjdlOWEzMzkzZjYiOlsicmVhZCJdLCJ1cm46ZmlsZXN0b3JlOmZpbGU6MDk1MzYxNGMtMmY0ZS00ZGU3LThlOWYtYjBlNDY4ZmFlNGUxIjpbInJlYWQiXSwidXJuOmZpbGVzdG9yZTpmaWxlOmQ0Y2IzOWIwLWQwOTItNDc1Ny05YTQ3LWYxMGJmNThkOTZhOSI6WyJyZWFkIl19LCJleHAiOjE2NTcxODYzMzQsIm5iZiI6MTY1NzE4NTQzNH0.1A9LE9SNpvrnWZsmX6X4hLiF-_c595sZrnBiy-HKtUg)

### Deployment instructions
None

### Author concerns
Script used to create JS API: 
Fliplet.FormBuilder.get().then(function(form) {
  form.fields.set([
    {
      _type: 'flCheckbox',
      selectAll: true,
      options: [{ label: 'zero' }, { label: 'two' }, { label: 'one' }]
    }
  ]);
});

2022-07-15 06:27 UTC, yogeshmsharma-xoriant reviewed
pls do minor changes

2022-07-15 06:27 UTC, yogeshmsharma-xoriant commented on js/components/checkbox.js
> +    console.log('Value');
pls remove this

2022-07-15 06:27 UTC, yogeshmsharma-xoriant commented on js/components/checkbox.js
> +      console.log(this.value);
pls remove all console.log

2022-07-15 06:27 UTC, yogeshmsharma-xoriant commented on templates/components/checkbox.build.hbs
> +          :id="name + '-' + 'a'"
what is this for?

2022-07-18 14:31 UTC, tonytlwu requested changes

2022-07-18 14:31 UTC, tonytlwu commented on js/components/checkbox.js
> +    updateCheckValue: function() {
I don't believe this function is necessary.

```suggestion
```

2022-07-18 14:31 UTC, tonytlwu commented on js/components/checkbox.js
> +    isSelectAll: {
This should not be necessary to render or manage the **Select all** option.

```suggestion
```

2022-07-18 14:31 UTC, tonytlwu commented on templates/components/checkbox.build.hbs
> +        :name="name"
I don't believe a `name` attribute is necessary.

```suggestion
```

2022-09-29 08:52 UTC, tonytlwu commented
Closing the PR now that it's implemented through https://github.com/Fliplet/fliplet-widget-form-builder/pull/454

2022-09-29 08:52 UTC, closed without merging