XOR-252 [FEAT] Ensure adding select all option for multiple checkbox form field
Fliplet/fliplet-widget-form-builder pull request #454
Opened 2022-07-18 11:28 UTC by NikitaJadhavXoriant

**Product areas affected**

fliplet-widget-form-builder

**What does this PR do?**
added _Select All_ option in checkbox form field
added via JS API as well, by passing _selectAll_ as true

**JIRA ticket**
[click here](https://weboo.atlassian.net/browse/XOR-252)

**Result**

https://user-images.githubusercontent.com/108272606/179501638-bbbd8d17-8a92-413c-b5ca-c89356468f66.mp4

**Checklist**
 None

**Testing instructions**
None

**Deployment instructions**
None

Author concerns
None

2022-07-18 13:00 UTC, yogeshmsharma-xoriant approved these changes
Looks ok to me

2022-09-21 09:21 UTC, squallstar requested changes
@NikitaJadhavXoriant you didn't address any of @tonytlwu's comments in https://github.com/Fliplet/fliplet-widget-form-builder/pull/451/files

2022-09-21 09:21 UTC, squallstar commented on translation.json
> +        "isSelectAll": {
This is incorrect, see https://github.com/Fliplet/fliplet-widget-form-builder/pull/451/files#r923398490

2022-09-21 09:21 UTC, squallstar commented on templates/configurations/form.interface.hbs
> +        <input type="checkbox" id="selectAll" name="selectAll" v-model="selectAll" v-on:input="required = false">
Comment not addressed https://github.com/Fliplet/fliplet-widget-form-builder/pull/451/files#r923305925

2022-09-21 09:21 UTC, squallstar commented on templates/components/checkbox.build.hbs
> +        <span class="option-item">\{{isSelectAll[0].label}}</span>
Comment not addressed https://github.com/Fliplet/fliplet-widget-form-builder/pull/451/files#r923399173

2022-09-21 09:21 UTC, squallstar commented on templates/components/checkbox.build.hbs
> +      <label v-on:click="checkAllHandler()">
Comment not addressed https://github.com/Fliplet/fliplet-widget-form-builder/pull/451/files

2022-09-21 10:28 UTC, NikitaJadhavXoriant commented
> @NikitaJadhavXoriant you didn't address any of @tonytlwu's comments in https://github.com/Fliplet/fliplet-widget-form-builder/pull/451/files


Hi Nick, Sorry for misunderstanding. I was waiting for readonly changes to be done after mergning of XOR-156, so Tony's suggested changes was on my local machine, which was not there in PR which you reviewed. But now I have pushed all Tony's suggested changes. So you will get all those changes in PR. Please review.

2022-09-27 09:22 UTC, squallstar commented
@tonytlwu this is for you to review 🙏🏻

2022-09-27 10:01 UTC, tonytlwu requested changes
Does not meet coding standards

2022-10-06 10:34 UTC, amolsuryawanshi47 commented on js/components/checkbox.js
> +
can you please remove new blank line

2022-10-06 10:36 UTC, NikitaJadhavXoriant commented on js/components/checkbox.js
> +
Done

2022-10-06 12:59 UTC, amolsuryawanshi47 submitted a review, later dismissed
Changes Looks ok to me

2022-10-07 13:27 UTC, tonytlwu requested changes

2022-10-07 23:40 UTC, amolsuryawanshi47 approved these changes
Changes Looks ok to me

2022-10-08 14:54 UTC, tonytlwu approved these changes

2022-10-10 09:39 UTC, squallstar approved these changes

2022-10-10 11:07 UTC, merged