XOR-629 [FEAT] Ensure ID generator Text Input Form field implemented
Fliplet/fliplet-widget-form-builder pull request #465
Opened 2022-10-28 17:34 UTC by NikitaJadhavXoriant

### Product areas affected

Widgets -> Add Form -> Select Text Input Field -> Check / Uncheck 'Have this form field act as an ID generator 

### What does this PR do?

Implemented code to convert Text input form field into ID generator.

### JIRA ticket

[JIRA](https://weboo.atlassian.net/browse/XOR-629)

### Result

https://user-images.githubusercontent.com/108272606/198697877-36c682e0-8490-4349-ac78-f96c2702f63a.mp4

### Checklist

None

### Deployment instructions

None

### Author concerns

None

2022-10-31 04:21 UTC, amolsuryawanshi47 submitted a review, later dismissed
Changes Looks ok to me

2022-10-31 14:39 UTC, tonytlwu requested changes

2022-10-31 14:39 UTC, tonytlwu commented on js/components/input.js
> +    Fliplet.FormBuilder.on('reset', this.onReset, this.$parent.id);
```suggestion
    Fliplet.FormBuilder.on('reset', this.onReset);
```

2022-10-31 14:39 UTC, tonytlwu commented on js/components/input.js
> +    Fliplet.FormBuilder.off('reset', this.onReset, this.$parent.id);
```suggestion
    Fliplet.FormBuilder.off('reset', this.onReset);
```

2022-10-31 14:39 UTC, tonytlwu commented on js/libs/core.js
> +    on: function(eventName, fn, id) {
Same for `off` and `emit`.

```suggestion
    on: function(eventName, fn) {
```

2022-10-31 14:39 UTC, tonytlwu commented on js/libs/core.js
> +      eventHub.$on(eventName + (id || ''), fn);
Same for `off` and `emit`.

```suggestion
      eventHub.$on(eventName, fn);
```

2022-10-31 15:33 UTC, NikitaJadhavXoriant commented on js/libs/core.js
> +      eventHub.$on(eventName + (id || ''), fn);
Done

2022-10-31 15:33 UTC, NikitaJadhavXoriant commented on js/libs/core.js
> +    on: function(eventName, fn, id) {
Done

2022-10-31 15:33 UTC, NikitaJadhavXoriant commented on js/components/input.js
> +    Fliplet.FormBuilder.off('reset', this.onReset, this.$parent.id);
Done

2022-10-31 15:33 UTC, NikitaJadhavXoriant commented on js/components/input.js
> +    Fliplet.FormBuilder.on('reset', this.onReset, this.$parent.id);
Done

2022-11-01 09:02 UTC, amolsuryawanshi47 approved these changes
Changes looks ok to me

2022-11-02 16:15 UTC, tonytlwu approved these changes

2022-11-02 16:16 UTC, merged