XOR-638 [Fix] Ensure when user try to click the label of the Checkbox , its not affecting the previous checkbox option
Fliplet/fliplet-widget-form-builder pull request #483
Opened 2023-03-29 07:56 UTC by NikitaJadhavXoriant

### Product areas affected

Widgets -> Form  -> Checkbox / Radio field 

### What does this PR do?

Implemented fix so that in Form component, when user try to click the label of the Checkbox, it's not affecting the previous checkbox option

### JIRA ticket

[JIRA](https://weboo.atlassian.net/browse/XOR-638)

### Result

https://user-images.githubusercontent.com/108272606/228465680-31895af8-0a0c-49af-96f4-9ed038e0bce6.mp4

### Checklist

none

### Testing instructions

none

### Deployment instructions

none

### Author concerns

none

2023-03-29 08:24 UTC, yogeshmsharma-xoriant submitted a review, later dismissed
looks ok

2023-03-29 08:50 UTC, tonytlwu requested changes

2023-03-29 08:50 UTC, tonytlwu commented on js/libs/core.js
> +      component.computed._isPreventClicked = function() {
```suggestion
      component.computed._labelName = function() {
```

2023-03-29 08:50 UTC, tonytlwu commented on js/libs/core.js
> +        return component.props._componentName.default === 'flCheckbox' || component.props._componentName.default === 'flRadio' ? '' : this.name;
```suggestion
        return ['flRadio', 'flCheckbox'].indexOf(component.props._componentName.default) > -1 ? '' : this.name;
```

2023-03-29 09:32 UTC, NikitaJadhavXoriant commented on js/libs/core.js
> +      component.computed._isPreventClicked = function() {
done changes

2023-03-30 07:24 UTC, tonytlwu approved these changes

2023-03-30 07:24 UTC, merged