ID-3032 [FIX] Fixed the default value set of the settings
Fliplet/fliplet-widget-form-builder pull request #497
Opened 2023-05-04 07:51 UTC by armine-fliplet

2023-05-15 14:18 UTC, tonytlwu requested changes

2023-05-15 14:18 UTC, tonytlwu commented on js/components/dateRange.js
> +        value = {
```suggestion
        value = null;
```

2023-05-15 14:18 UTC, tonytlwu commented on js/components/dateRange.js
> +          start: moment(value, 'YYYY-MM-DD', true).isValid() ? this.formatDate(value) : this.formatDate(),
```suggestion
          start: this.formatDate(value),
          end: this.formatDate(value)
```

2023-05-15 14:20 UTC, tonytlwu commented on js/components/dateRange.js
> +      }
```suggestion
      } else if (value.start > value.end) {
        value.end = value.start;
      }
```

2023-05-16 06:18 UTC, armine-fliplet commented on js/components/dateRange.js
> +      default: {
I was getting an error in `set` function, but it's from the API, it's okay now. Fixed!

2023-05-16 08:25 UTC, armine-fliplet commented on templates/configurations/dateRange.interface.hbs
> +<div v-else class="form-group">
I had a task in the current phase, and in the comments Sofi and you have left a comment about adding 3rd option.

2023-05-16 10:41 UTC, tonytlwu approved these changes

2023-05-16 10:50 UTC, merged