ID-3359 [FIX] Ensure Matrix field's default value display correctly when "User's profile" type is selected
Fliplet/fliplet-widget-form-builder pull request #544
Opened 2023-07-19 07:10 UTC by NikitaJadhavXoriant

**Product areas affected**

Studio -> Form -> Form Fields -> Matrix field

**What does this PR do?**

Implemented code, so Matrix field's default value display correctly when "User's profile" type is selected

**JIRA ticket**

[click here](https://weboo.atlassian.net/browse/ID-3359)

**Result**

https://github.com/Fliplet/fliplet-widget-form-builder/assets/108272606/298dc34b-8f90-4238-8560-7f1d4133951e

**Checklist**

None

**Testing instructions**

None

**Deployment instructions**

None

**Author concerns**

None

2023-08-11 14:09 UTC, tonytlwu requested changes

2023-08-11 14:09 UTC, tonytlwu commented on js/libs/form.js
> +                      _.some(value, function(col, row) {
```suggestion
                      var rowFound = _.some(value, function(col, row) {
```

2023-08-11 14:09 UTC, tonytlwu commented on js/libs/form.js
> +                      if (!rowFlag) {
```suggestion
                      if (!rowFound) {
```

2023-08-11 14:09 UTC, tonytlwu commented on js/libs/form.js
> +                      var val = rowOpt.id ? rowOpt.id : rowOpt.label;
```suggestion
                      var val = rowOpt.id || rowOpt.label;
```

2023-08-29 10:47 UTC, tonytlwu requested changes

2023-08-29 14:24 UTC, NikitaJadhavXoriant commented on js/libs/form.js
> +              ? field.defaultValueKey
Hi @tonytlwu, yes I have verified this change, as per this [flow](https://docs.google.com/presentation/d/1ZcDdKZthUujPP_VuBXX9J5fj2HWTdrsBAdarndBgmnM/edit#slide=id.g1fb36f71a8b_0_1), we need to reset to defaultValueKey and if defaultValueKey is undefined we need to set the value as blank and not to field.name that is why I removed that. Yes, I will ask Kathi for regression testing.

2023-08-29 14:25 UTC, NikitaJadhavXoriant commented on js/libs/form.js
> +                    if ((!field.defaultValueKey && matrixKey) || (field.defaultValueKey.indexOf(val) !== -1 && matrixKey)
Done

2023-09-04 15:58 UTC, tonytlwu approved these changes
@inna-bieshulia This is ready for testing

Skip compile: 
Includes translation: 
Initiative: 
Impact: High
Affected: All field types that support default value settings
Verify: All types of default value configurations are working on all field types and the resetting behaviours are correct

2023-09-05 06:55 UTC, merged